### ISSUE TITLE
When using Ubuntu....

### ISSUE THREAD

**Issue by mlongval** [maxhu08/dotfiles#1]
Hi,

When using your dotfiles on Ubuntu 24.04 (inside a Distrobox container), I ran into an issue. 

The "build-essential", "fzf", "python3-all-venv", "nodejs" and "npm"  packages for Ubuntu MUST be installed inside the container BEFORE the first run of "nvim" after the "stow nvim"  command. 

If not, the initialization of "nvim"  upon first run will throw errors for "fzf" that will disappear after installation of the "fzf" package, but it will continue to throw errors for Mason, even after the "build-essential" package is installed. 

I tried deleting the link inside .config, but I had to delete "$HOME/.local/share/nvim", for it to do a clean install and work as expected. 

Thanks for the great dotfiles!

Cheers from Canada!

**Comment by maxhu08** [comment]
Thank you, I've added a notice about that to the readme
